// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health-check.sql

package db

import (
	"context"
)

const isReady = `-- name: IsReady :one
SELECT EXISTS(
    SELECT 1
)
`

func (q *Queries) IsReady(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, isReady)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
