// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppWordList struct {
	ID    int32
	Title string
	Words string
}

type AppWordsPicked struct {
	ID         int32
	Word       string
	WordListID int32
	PickedAt   pgtype.Timestamp
}

type AppWordsPickedHistory struct {
	ID         int32
	Word       string
	WordListID int32
	PickedAt   pgtype.Timestamp
}
