// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: word-list-add.sql

package db

import (
	"context"
)

const createWordList = `-- name: CreateWordList :one
INSERT INTO app.word_lists (title, words)
VALUES ($1, $2)
RETURNING id
`

type CreateWordListParams struct {
	Title string
	Words string
}

func (q *Queries) CreateWordList(ctx context.Context, arg CreateWordListParams) (int32, error) {
	row := q.db.QueryRow(ctx, createWordList, arg.Title, arg.Words)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const existsWordList = `-- name: ExistsWordList :one
SELECT EXISTS (
	SELECT 1
	FROM app.word_lists
	WHERE title = $1
)
`

func (q *Queries) ExistsWordList(ctx context.Context, title string) (bool, error) {
	row := q.db.QueryRow(ctx, existsWordList, title)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
