// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: word-list-overview.sql

package db

import (
	"context"
)

const listWordLists = `-- name: ListWordLists :many
SELECT id, title, words FROM app.word_lists
ORDER BY Title
`

func (q *Queries) ListWordLists(ctx context.Context) ([]AppWordList, error) {
	rows, err := q.db.Query(ctx, listWordLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppWordList
	for rows.Next() {
		var i AppWordList
		if err := rows.Scan(&i.ID, &i.Title, &i.Words); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
