// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: word-list-pick.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearWordsPickedFromList = `-- name: ClearWordsPickedFromList :exec
DELETE FROM app.words_picked
WHERE word_list_id = $1
`

func (q *Queries) ClearWordsPickedFromList(ctx context.Context, wordListID int32) error {
	_, err := q.db.Exec(ctx, clearWordsPickedFromList, wordListID)
	return err
}

const createWordPicked = `-- name: CreateWordPicked :exec
INSERT INTO app.words_picked (word_list_id, word)
VALUES ($1, $2)
`

type CreateWordPickedParams struct {
	WordListID int32
	Word       string
}

func (q *Queries) CreateWordPicked(ctx context.Context, arg CreateWordPickedParams) error {
	_, err := q.db.Exec(ctx, createWordPicked, arg.WordListID, arg.Word)
	return err
}

const getWordListHistory = `-- name: GetWordListHistory :many
SELECT word, picked_at
FROM app.words_picked_history
WHERE word_list_id = $1
ORDER BY picked_at DESC
LIMIT 14
`

type GetWordListHistoryRow struct {
	Word     string
	PickedAt pgtype.Timestamp
}

func (q *Queries) GetWordListHistory(ctx context.Context, wordListID int32) ([]GetWordListHistoryRow, error) {
	rows, err := q.db.Query(ctx, getWordListHistory, wordListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWordListHistoryRow
	for rows.Next() {
		var i GetWordListHistoryRow
		if err := rows.Scan(&i.Word, &i.PickedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWordListToPick = `-- name: GetWordListToPick :one
SELECT wl.id, wl.title, wl.words, (COALESCE(STRING_AGG(wp.word, ','), ''))::text as words_picked
FROM app.word_lists wl
LEFT JOIN app.words_picked wp ON wl.id = wp.word_list_id
WHERE wl.id = $1
GROUP BY wl.id, wl.title, wl.words
`

type GetWordListToPickRow struct {
	ID          int32
	Title       string
	Words       string
	WordsPicked string
}

func (q *Queries) GetWordListToPick(ctx context.Context, id int32) (GetWordListToPickRow, error) {
	row := q.db.QueryRow(ctx, getWordListToPick, id)
	var i GetWordListToPickRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Words,
		&i.WordsPicked,
	)
	return i, err
}
